cluster:
  standalone:
    url: jdbc:h2:~/memorydb
    user_name: sa
cache:
  guava:
queue:
  disruptor:
naming:
  jetty:
    host: localhost
    port: 10800
    context_path: /
remote:
  gRPC:
    host: localhost
    port: 11800
agent_gRPC:
  gRPC:
    host: localhost
    port: 11800
agent_jetty:
  jetty:
    host: localhost
    port: 12800
    context_path: /
agent_stream:
  default:
    buffer_file_path: ../buffer/
    buffer_offset_max_file_size: 10M
    buffer_segment_max_file_size: 500M
configuration:
  default:
alerting:
  default:
ui:
  jetty:
    host: localhost
    port: 12800
    context_path: /
jetty_manager:
  jetty:
gRPC_manager:
  gRPC:
storage:
  h2:
    url: jdbc:h2:~/memorydb
    user_name: sa